[
    {
        "title": "Fix xAI bug"
    },
    {
        "author": {
            "login": "PR Description"
        },
        "body": "```\r\nAssertionError: Unsupported xai.\r\nSupported llm providers are: bedrock, ollama, azure_openai, cohere, anthropic, dashscopexai, fireworks, huggingface, mistralai, openai, google_vertexai, groq, together, google_genai\r\n```\r\n\r\n```\r\n$ git diff 40a6c409755b73b9fcf3c6afbf33dc608f52546a~ 40a6c409755b73b9fcf3c6afbf33dc608f52546a      \r\ndiff --git a/gpt_researcher/llm_provider/generic/base.py b/gpt_researcher/llm_provider/generic/base.py\r\nindex 05536f6f..4c4757c3 100644\r\n--- a/gpt_researcher/llm_provider/generic/base.py\r\n+++ b/gpt_researcher/llm_provider/generic/base.py\r\n@@ -17,6 +17,7 @@ _SUPPORTED_PROVIDERS = {\r\n     \"huggingface\",\r\n     \"groq\",\r\n     \"bedrock\",\r\n+    \"dashscope\"\r\n     \"xai\",\r\n }\r\n```\r\n\r\nOne of the recent git merges broke the xAI functionality. Note the missing comma. Nobody's to blame, just git's annoying merge logic ._.\r\n\r\nThis means the xAI functionality will be broken until the next release unfortunately."
    },
    {
        "author": {
            "login": "assafelovic"
        },
        "body": ""
    },
    {
        "author": {
            "login": "winsonluk"
        },
        "body": "@assafelovic yet another bug fix...this means the xAI functionality will be broken until the next release unfortunately."
    }
]