[
    {
        "title": "Add context when test fails due to unexpected log entries"
    },
    {
        "author": {
            "login": "PR Description"
        },
        "body": "## Checklist before requesting a review\r\n\r\n- [x] I have read the CONTRIBUTING document.\r\n- [x] I have performed a self-review of my code.\r\n\r\n## Description\r\n\r\nNow we use the Symfony error handler, any non blocking PHP error is now sent to the error handler with a `['exception' => ErrorException]` context. We can therefore display this context in the tests results. This is a bit verbose, but it is often hard to find the exact source of the error without this information.\r\n\r\nBefore:\r\n```\r\nUnexpected entries in log in tests\\units\\ApplianceTest::GLPITestCase::tearDown:\r\nArray\r\n(\r\n    [0] => Array\r\n        (\r\n            [channel] => glpi\r\n            [level] => Warning\r\n            [message] => Warning: Undefined array key \"pictures\" at AssetImage.php line 90\r\n        )\r\n\r\n)\r\n```\r\n\r\nAfter:\r\n```\r\nUnexpected entries in log in tests\\units\\ApplianceTest::GLPITestCase::tearDown:\r\nArray\r\n(\r\n    [0] => Array\r\n        (\r\n            [channel] => glpi\r\n            [level] => Warning\r\n            [message] => Warning: Undefined array key \"pictures\" at AssetImage.php line 90\r\n            [context] => Array\r\n                (\r\n                    [exception] => Array\r\n                        (\r\n                            [message] => Warning: Undefined array key \"pictures\" at AssetImage.php line 90\r\n                            [trace] => #0 /var/www/glpi/src/Appliance.php(120): Appliance->managePictures(Array)\r\n#1 /var/www/glpi/src/CommonDBTM.php(1356): Appliance->prepareInputForAdd(Array)\r\n#2 /var/www/glpi/phpunit/functional/ApplianceTest.php(200): CommonDBTM->add(Array)\r\n#3 /var/www/glpi/vendor/phpunit/phpunit/src/Framework/TestCase.php(1201): tests\\units\\ApplianceTest->testMetaSearch()\r\n#4 /var/www/glpi/vendor/phpunit/phpunit/src/Framework/TestCase.php(498): PHPUnit\\Framework\\TestCase->runTest()\r\n#5 /var/www/glpi/vendor/phpunit/phpunit/src/Framework/TestRunner/TestRunner.php(84): PHPUnit\\Framework\\TestCase->runBare()\r\n#6 /var/www/glpi/vendor/phpunit/phpunit/src/Framework/TestCase.php(349): PHPUnit\\Framework\\TestRunner->run(Object(tests\\units\\ApplianceTest))\r\n#7 /var/www/glpi/vendor/phpunit/phpunit/src/Framework/TestSuite.php(408): PHPUnit\\Framework\\TestCase->run()\r\n#8 /var/www/glpi/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(62): PHPUnit\\Framework\\TestSuite->run()\r\n#9 /var/www/glpi/vendor/phpunit/phpunit/src/TextUI/Application.php(201): PHPUnit\\TextUI\\TestRunner->run(Object(PHPUnit\\TextUI\\Configuration\\Configuration), Object(PHPUnit\\Runner\\ResultCache\\DefaultResultCache), Object(PHPUnit\\Framework\\TestSuite))\r\n#10 /var/www/glpi/vendor/phpunit/phpunit/phpunit(104): PHPUnit\\TextUI\\Application->run(Array)\r\n#11 /var/www/glpi/vendor/bin/phpunit(122): include('/var/www/glpi/v...')\r\n#12 {main}\r\n                        )\r\n\r\n                )\r\n\r\n        )\r\n\r\n)\r\n\r\n```"
    },
    {
        "author": {
            "login": "trasher"
        },
        "body": ""
    },
    {
        "author": {
            "login": "AdrienClairembault"
        },
        "body": ""
    },
    {
        "author": {
            "login": "AdrienClairembault"
        },
        "body": "Lint error seems unrelated ?"
    },
    {
        "author": {
            "login": "cedric-anne"
        },
        "body": "> Lint error seems unrelated ?\r\n\r\nFixed by #18912."
    }
]